### ISSUE TITLE
Adding summary rows after a single row divider

### ISSUE THREAD

**Issue by nyurik** [Nukesor/comfy-table#104]
### A detailed description of the feature you would like to see added.

I would like to be able to draw a table with a summary row, e.g. something of this style:

```
 Hello   there
═══════════════
 a       b
 a       b
 a       b
 a       b
───────────────
 c       d
```

Is it possible?  Thanks!

### Explain your usecase of the requested feature

Show column totals

**Comment by Nukesor** [comment]
Sadly it's not possible.
Individual styling of delimiters between rows wasn't ever considered when building this libarary.

I cannot think of a non-hacky ways to retrofit this feature without introducing huge breaking changes the project, which I would say that this is a feature that'll probably not be added. Sorry mate.
