### ISSUE TITLE
Doc clarification on boundaries

### ISSUE THREAD

**Issue by andrewbaxter** [Nukesor/comfy-table#111]
### A detailed description of the feature you would like to see added.

The documentation for e.g. UpperBoundary or LowerBoundary just say that they're upper boundaries and lower boundaries.  I'd like to know more about what they mean or how they're used.

For instance, does lower boundary mean it won't wrap unless the content is longer than that value? Or does it mean that the cell is padded to that width?

Does upper boundary mean even if there's extra space the column will be wrapped at that length? Or that the column won't be wrapped below this width?

Do these affect wrapping priority? What's the default constraint for columns if not specified? The docs say extra column constraints are ignored, but what happens if you provide fewer constraints than columns?

### Explain your usecase of the requested feature

Avoiding trial and error

### Alternatives

Trial and error

**Comment by Nukesor** [comment]
Lower boundary means, that that column will be at least as wide as specified. If the content isn't as long as that boundary, the it will be padded.
If it the column has longer content and is allowed to grow, the column may take more space.

Upper boundary means, that that column will be at most as wide as specified.
If the content of that column is smaller than that width, it may also be smaller than that width.

Those boundaries don't inherently have something to do with wrapping.
The formatting logic checks how much each space each column is supposed/allowed to have. Once that is determined, the actual wrapping starts. Constraints are useful to enforce a certain format for your columns.

**Comment by andrewbaxter** [comment]
Ah thanks!  So the upper boundary has to do with wrapping, but not allocation when multiple columns are wrapped, and the lower boundary has to do with padding?

To be clear, it would be awesome if this were in the docs (hence the issue).  If I forget, that's the first place I'll go and it would probably help people new to the project too.

**Comment by Nukesor** [comment]
Fixed in 941003d  :)
