### ISSUE TITLE
[Bug] Integer overflow on large column

### ISSUE THREAD

**Issue by thomas-k-cameron** [Nukesor/comfy-table#112]
### Describe the bug

It was initially reported here. 

https://github.com/apache/arrow-datafusion/issues/6524

Padding uses `u16`; It caused integer overflow on large table.

I wonder if it would be possible to allow users to check how big the table is going to be so that it can avoid causing overflow.

Proposed changes:

1. Wrap returning result with `Result<_, ComfyTableError>`
This ones fixes the issue but it causes braking changes.

2. Change `u16` to `u64`
It should be less-likely for this to happen.

I implemented `1.` on my fork, so if you are moving forward with `1`, I'd love to create a PR.

### Steps to reproduce

Details in the `arrow-datafusion` issue.

### Logs (if applicable)

Details in the `arrow-datafusion` issue.

### Operating system

NA

### Comfy-table version

v6.1.4

**Comment by Nukesor** [comment]
I created a PR, which (I assume) fixes the panic. It would still be awesome, if you could add a testcase and/or test whether this works for you :)

**Comment by thomas-k-cameron** [comment]
Let me look into it.
