### ISSUE TITLE
Means to check if the natural table width is wider than terminal

### ISSUE THREAD

**Issue by matatk** [Nukesor/comfy-table#116]
### A detailed description of the feature you would like to see added.

I would like the means, e.g. a function on `Table`, to check if the natural width of the table (i.e. the widest row, after padding and borders are applied, but before any columns are truncated to fit) is wider than the terminal.

The function might return a bool, or perhaps the number of characters of overflow.

This would enable me to know whether any of the columns are being truncated when the table is rendered using `ContentArrangement::Dynamic`.

If the program isn't running in a terminal, just returning `false` or `0` seems logical (the rationale for that is explained below).

### Explain your usecase of the requested feature

Some columns are more important than others. In the event that there isn't space to show the whole table, I'd like to set width constraints on the columns I don't mind truncating, so that the more important columns get as much space as possible.

If the program isn't running in a terminal, I wouldn't want to do any truncation, so in this case, I would expect the function to return `false`/`0`, as if the "terminal" was wide enough to accommodate the table.

### Alternatives

1. A priority order (e.g. of column indices) could be given, to determine which columns will get more space, though this could get complicated if, e.g. some columns are equally important, and it also wouldn't help me give specific widths to columns.

   I think these two approaches could be complimentary, though for my use case, I know the likely upper bounds for widths on the columns I'd rather truncate, so having that control would be better.

2. Another option would be to change `Table::width()` to return the table's natural width (i.e. with padding and borders, but before truncation). I could then compare it to the result of `crossterm::terminal::size()` manually. However, that might be too much of a breaking change for `comfy_table` and it's not as neat as adding an `overflow()` function, because I still have to test for the overflow, and that forces me to depend explicitly on `crossterm` just to do that.

### Additional context

Thank you for this library; it's great!

**Comment by Nukesor** [comment]
I see how this would be convenient, but this is also a very specific and rather edge-casey use case.

Due to this, I don't thing this needs to be a dedicated function though, as you can already do this with the current functions:

Call `Table::column_max_content_widths().iter().sum()` to get the max width of content in the natural table.
Then, use some library like crossterm to determine the current terminal length `crossterm::terminal::size()`.

Now, you can go ahead and do all logic you desire.

**Comment by matatk** [comment]
Thanks for your thoughts, and suggestion @Nukesor; this was helpful. (Also sorry for my very laggy reply; I wasn't able to come back to this for a while, but have now.)
