### ISSUE TITLE
[Feature] Colored borders

### ISSUE THREAD

**Issue by jordemort** [Nukesor/comfy-table#127]
### A detailed description of the feature you would like to see added.

I'd love to be able to choose a color for my borders!

### Explain your usecase of the requested feature

I think having colored borders would help me develop a distinctive look for my app.

**Comment by Nukesor** [comment]
comfy-table tries to be very minimalistic and "basic".

I think [prettytable-rs](https://github.com/phsym/prettytable-rs#customize-look-and-feel-of-a-table) is a much better fit for such features, as this is also a design goal they're going for :).

Closing as wont do.

**Comment by fgimian** [comment]
@Nukesor Do you think you would reconsider this? Just a single function which would set the color for the entire border would be sufficient. Currently this does feel like a missing feature given how extensively this awesome library already supports colors everywhere else.

I respect your decision if not, but just thought I'd ask again in case you would reconsider.

Cheers
Fotis
