### ISSUE TITLE
Horizontal lines

### ISSUE THREAD

**Issue by marcbowes** [Nukesor/comfy-table#129]
### A detailed description of the feature you would like to see added.

I'd like to be able to control when horizontal lines are drawn, so that I can visually group content. The only way to do this at the moment (I think) is to use newlines within cells, which makes the table population code messy.

### Explain your usecase of the requested feature

When rendering complex results, I'd like to make it more visually obvious how the data are grouped. A good example is the table in the readme of https://github.com/ept/hermitage/tree/master.

### Alternatives

I can use newlines in cells to append cell values of all other cells in the group.

**Comment by Nukesor** [comment]
Did you try to add a full row, just like in the example readme that you linked?
