### ISSUE TITLE
Macros to convert several values into cells

### ISSUE THREAD

**Issue by jmg-duarte** [Nukesor/comfy-table#131]
### A detailed description of the feature you would like to see added.

Instead of:
```rust
table.add_row([
    Cell::new(special_value),
    Cell::new("normal string"),
    Cell::new(something_else)
])
```

Have:
```rust
table.add_row(row![
    special_value,
    "normal string",
    something_else
])
```

Which expands to the code above.

### Explain your usecase of the requested feature

I'm currently moving off of `prettytable` which had a bunch of utility macros like this. They came in really handy when using different types, because the code was "really short" (read, the size of all required information to someone reading it).

With the existing API, the only thing I can do is write the extra `Cell::new`.

I noticed there's https://github.com/Nukesor/comfy-table/issues/50, but for my request a proc-macro shouldn't be needed, a `macro_rules` should suffice.

### Alternatives

The alternative is of course do them all manually.

I totally understand if you're not interested in adding this as "more characters to type" isn't a huge complaint, and the code you write for the table isn't constantly changing.

_But_, the crate would become easier to migrate to, off of `prettytable` 👀 

### Additional context

I've sketched out a demo that I can submit as PR if you're interested:
```rust
macro_rules! _inner_row {
    ($value:expr) => {
        Cell::new($value)
    };
    ($value:expr, $($values:expr), +) => {
        [Cell::new($value), _inner_row!($($values)+)]
    };
}

macro_rules! row {
    ($value:expr) => {
        [_inner_row!($value)]
    };
    ($value:expr, $($values:expr), +) => {
        _inner_row!($value, $($values)+)
    };
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e0102c01bf07bb3a0831a379c8e40e2

**Comment by Nukesor** [comment]
Sorry for the delay.

I don't really see a benefit to this. `Rows` implements `impl<T: Into<Cells>> From<T> for Row`, with `pub struct Cells(pub Vec<Cell>).

And 
```rs
impl<T> From<T> for Cells
where
    T: IntoIterator,
    T::Item: Into<Cell>
```

So you can just say:

```rs
table.add_row(Row::from(vec![
    special_value,
    "normal string".to_string(),
    something_else,
]))
```

IMO the overhead of having macros like this isn't worth it, if you can relatively easily cover such usecases with trait implementations.

**Comment by Nukesor** [comment]
I also updated the docs for all `add_row[s]*` functions to make this a bit more clear:
https://github.com/Nukesor/comfy-table/commit/c1d1403a57382b70e40abefce91bd5c0cef572e2

**Comment by jmg-duarte** [comment]
Agreed with the take on macros. Closing!
