### ISSUE TITLE
[Bug] Setting background or foreground color breaks alignment

### ISSUE THREAD

**Issue by solaeus** [Nukesor/comfy-table#132]
### Describe the bug

Setting a background or foreground color on a cell causes the table to display incorrectly. I'm using the latest version of kitty as my terminal and the library works perfectly without color.

![Screenshot from 2023-12-27 00-45-27](https://github.com/Nukesor/comfy-table/assets/112188538/36198a62-ce6b-473b-af8c-e042f6c9369e)

![Screenshot from 2023-12-27 00-45-07](https://github.com/Nukesor/comfy-table/assets/112188538/85ff6394-7f30-4b0c-a076-e5620a913e2a)

### Steps to reproduce

This cell produces normal output.
```rust
Cell::new(inner)
```

This produces the erroneous output shown above.
```rust
Cell::new(inner).bg(Color::Green)
```

### Operating system

Fedora 39

### Comfy-table version

7.1.0

### Additional context

I reproduced the problem in Gnome Terminal.

**Comment by Nukesor** [comment]
Sorry, nested tables aren't supported or planned :)

[Table](https://github.com/Nukesor/comfy-table#contributing)

> Some things however will most likely not be added to the project since they drastically increase the complexity of the library or cover very specific edge-cases.
>
>Such features are:
>
>    Nested tables
>    Cells that span over multiple columns/rows
>    CSV to table conversion and vice versa

**Comment by Nukesor** [comment]
Oh.

While not actively supported, your usecase might still work with the `custom_styling` feature enabled.

It tanks the performance by ~25% though, so don't use it for large tables :)
