### ISSUE TITLE
Multiple colors in a cell

### ISSUE THREAD

**Issue by Eragon615** [Nukesor/comfy-table#136]
### A detailed description of the feature you would like to see added.

Can we get a way to do several colors in a cell, such as on different words?

### Explain your usecase of the requested feature

I'm migrating a project from pretty tables, and in my project I'm pulling tags on items in netbox and displaying them. I have them written on the same color as the tag in netbox, and in pretty tables I just made a table of all tags and nested it in a cell with no borders. Looked pretty good. But since you've already stated that nested tables aren't going to be a feature, I'm looking for another way to achieve something like that. I've also tried passing in text formatted with the colored crate, but it loses formatting in a cell. 

### Alternatives

I suppose interop with the colored library would be cool, or else just add the ability to pass in per word formatting? Not sure the best way here.

**Comment by Nukesor** [comment]
So there's currently an "interop" with other libraries.

comfy-table has the `custom_styling` feature flag. It's hidden behind a feature, as all text inside of your table will be parsed for ascii escape characters.

It's a fairly untested feature that was written by a contributor, but from what I've seen it works quite well.

Just enable that feature, and use any other terminal library to color your output.

**Comment by Eragon615** [comment]
Sounds like that should work. I'll give it a go. Guess I should also read the feature flags on a crate more carefully in the future.

**Comment by Nukesor** [comment]
> Sounds like that should work. I'll give it a go. Guess I should also read the feature flags on a crate more carefully in the future.

Well, feature flags are the one thing that're not properly documentable right now. It's also pretty hard to write docs for feature-flag-gated functionality, as conditional compilation makes things a bit akward. (I.e. does one create docs for each set of possible feature flags? What are possible sets of feature flags?).

So don't worry, this isn't your fault ;D

**Comment by Nukesor** [comment]
Closing for now :)
Feel free to re-open if you're encountering any problems.
