### ISSUE TITLE
[Feature] Sorting

### ISSUE THREAD

**Issue by 9999years** [Nukesor/comfy-table#139]
### A detailed description of the feature you would like to see added.

It would be nice to be able to sort a table by a column's value. Alternatively, a custom sorting function could be used to compare two rows with each other.

### Explain your usecase of the requested feature

It would be a little annoying to build up a `Vec` with all the rows, sort it, and then add it to the table, and the table needs to track all the rows anyways.

### Alternatives

I could build up a `Vec` and sort it myself.

**Comment by Nukesor** [comment]
To be honest, i think this is something that shouldn't be added to comfy-table, as it shouldn't be much more than a few lines of additional code to do this yourself.

Comfy-table can build tables from nested vecs as long as stuff inside of it implements ToString, so the way to go would be to build an array of vecs and simply add them in one go via `add_rows`. Maybe I'm overlooking something, but this shouldn't be more annoying than simply building the table as of now (but with vecs), calling the sorting function you want to call and run `table.add_rows(rows)` afterwards.
