### ISSUE TITLE
Make cells content shrinkable

### ISSUE THREAD

**Issue by soywod** [Nukesor/comfy-table#151]
### A detailed description of the feature you would like to see added.

Sometimes, you don't want content to be on multiple line. If I don't mistake, there is no way to avoid this behaviour right now. It could be nice to make cells "shrinkable", with ellipsis, like on this screenshot: https://github.com/soywod/himalaya.

### Explain your usecase of the requested feature

When you want a condensed table where no cell expands on 2+ lines.

**Comment by Nukesor** [comment]
You can set a `max_height` on the `Row` struct: https://docs.rs/comfy-table/latest/comfy_table/struct.Row.html#method.max_height

Would this solve your issue?

**Comment by soywod** [comment]
I missed this option, it is exactly what I had in mind. Thank you!
