### ISSUE TITLE
Example of comfy-table usage

### ISSUE THREAD

**Issue by soywod** [Nukesor/comfy-table#153]
I did not find any place to simply share an information, so I open an issue. First I wanted to thank you for the great lib. I refactored my hand-made table system with yours and I am happy so far. I just wanted to share this information. I used the Markdown preset by default, here how the integration looks like:

<https://github.com/pimalaya/himalaya>

I may come to you if my users find bugs, in order to improve your work.

Have a great day!

**Comment by Nukesor** [comment]
Happy to hear that :heart: 

I hope that you won't run into any issues. However, so far it's already being used by a few [pretty popular projects](https://crates.io/crates/comfy-table/reverse_dependencies), so I guess you'll be fine :grin:
