### ISSUE TITLE
Make the table clonable

### ISSUE THREAD

**Issue by soywod** [Nukesor/comfy-table#154]
### A detailed description of the feature you would like to see added.

Add the `#[derive(Clone)]` to `Table` struct.

### Explain your usecase of the requested feature

Clone a table.

### Additional context

From my understanding, nothing is preventing the derive. The table is composed of clonable elements, except for `Column` that is also composed of clonable elements. So make the table clonable should be straightforward.

**Comment by Nukesor** [comment]
I agree that it wouldn't be an issue.
I'm just curious what your actual usecase of this is :D 

Comfy-table follows the concept of "display-only", meaning that data manipulation is done outside of the table and once everything is in order, the Table is created via the builder pattern and displayed.

You can certainly append further data to it, but I cannot come up with a scenario where you would want to clone a table.

**Comment by soywod** [comment]
> Comfy-table follows the concept of "display-only", meaning that data manipulation is done outside of the table and once everything is in order, the Table is created via the builder pattern and displayed.

I understand the concept and it makes sense. That said, adding the `Clone` derive should not impact anything. Especially that 90% is already `Clone` ready. I try to integrate your lib with [`ratatui`](https://github.com/ratatui/ratatui), and I needed to clone tables for debugging / testing purpose.

**Comment by Nukesor** [comment]
Could you give me an exact use-case :D?

I just want to understand each feature request in full, before I add something to any of my projects. It's just a thing I always do, it helps to get a better understanding how consumers of this library actually use it. Debugging/testing purposes is a bit vague^^

**Comment by soywod** [comment]
Let's be honest, I don't have a valid-enough use-case. But do you have clone use-cases for `Cell` and `Row`? If not (which looks like, according to the code — I did not find a single `.clone()` on them), how come they derive `Clone` then?

I respect (and agree about) the fact to be aware of every single feature request. But in this case, if there is no clone use-case for `Cell` and `Row` then derives need to be more consistent. Either derive `Clone` everywhere or nowhere. If there is clone use-case I missed, then my bad. You can discard my request as I do not have a valid use-case.

**Comment by Nukesor** [comment]
Good points. Seems I added Clone on auto-pilot without thinking whether it's necessary. The clone has been there since the very early days.

I don't see any usages of clone in either the code, test code, nor in any of the projects where I use comfy-table myself...

In that case, let's add it for consistency sake.

**Comment by Nukesor** [comment]
Implemented in f6c7d24
