### ISSUE TITLE
smaller truncate character

### ISSUE THREAD

**Issue by jdx** [Nukesor/comfy-table#161]
### A detailed description of the feature you would like to see added.

to save a couple characters, it'd be great if comfy-table used `…` instead of `...` or if the truncate character was customizable

### Explain your usecase of the requested feature

tiny screen

**Comment by Nukesor** [comment]
Sounds reasonable :)

I would go for a new option on the `Table` i.e. something like `set_truncate_indicator`. That was the best name I came up with from the top of my head, though I feel like that's not the best name :D. I don't like "character" in the setter's name as it could be a string.


I won't build this myself, feel free to take a stab at it!
Please add proper tests, thanks!

**Comment by Nukesor** [comment]
closed in #163

**Comment by Nukesor** [comment]
Will push a release once #162 is merged :0
