### ISSUE TITLE
Wrong boarder alignment with single column

### ISSUE THREAD

**Issue by PrivateRookie** [Nukesor/comfy-table#18]
when table only has 1 column, column header border doesn't align with column content

![image](https://user-images.githubusercontent.com/21262091/100890429-353fc100-34f3-11eb-8720-35647f6d0e43.png)

both ascii and utf8 preset have this bug.

version: 1.3.0

how to fix it?

**Comment by Nukesor** [comment]
I'm not able to reproduce this issue...
Could you post your code?

I tried to reproduce it with this little snippet:
```
    let mut table = Table::new();
    table
        .set_header(&vec!["Header1"])
        .add_row(&vec!["One One"])
        .add_row(&vec!["Two One"])
        .add_row(&vec!["Three One"]);

    println!("{}", table.to_string());
```

**Comment by PrivateRookie** [comment]
Sorry, it's my fault, thread that prints this table shares stdout with other thread, so output without new line from other thread cause this wired problem.

Should I close this issue myself ?

**Comment by Nukesor** [comment]
No problem :)

I'm happy I could help you debug your issue ;D
