### ISSUE TITLE
fill screen with table

### ISSUE THREAD

**Issue by Corfucinas** [Nukesor/comfy-table#22]
Hi, 

Is it possible to set the table to expand and cover a certain size of the terminal?

**Comment by Nukesor** [comment]
As a matter of fact, this isn't yet possible, the table will always use less width, if it doesn't need expand.

However, I would be ok with a feature, which actually enforces the remaining space to be completely used.
Right now we stop after successfully assigning each column as much space as it can get:
https://github.com/Nukesor/comfy-table/blob/master/src/utils/arrangement.rs#L202

It might be a good idea to add another `ContentArrangement` enum.
Maybe something like `DynamicFullWidth`?

If this is set, the remaining width could then be distributed to all columns in relation to the respective column-width.

**Comment by Corfucinas** [comment]
Amaizing.

I have a Python package I want to rewrite to Rust as an exercise. Trying to figure out the libraries to use, I'm will in the process of learning the whole complex syntax, but if you're up for it, we can try to work on this feature together.

**Comment by Nukesor** [comment]
I thought a little about it and I think I managed to find a relatively elegant solution for the problem.
The current implementation simply distributes the remaining space between all columns.

I'm still not sure if this is the best approach or whether we should distribute the space depending on each column's width, though.

**Comment by Nukesor** [comment]
@Corfucinas The PR should now be in a well-tested and polished state :)
Feel free to go ahead and review it.

If you're ok with the current changes, I'll go ahead and merge it.

**Comment by Corfucinas** [comment]
@Nukesor 

Amaizing. I'll review it tomorrow in the office, thanks!
