### ISSUE TITLE
Get the width of a column

### ISSUE THREAD

**Issue by Mohammadreza99A** [Nukesor/comfy-table#29]
I am wondering if it is possible to get the width of a column?
I have a table like this:
```
table
    .load_preset(UTF8_FULL)
    .apply_modifier(UTF8_ROUND_CORNERS)
    .set_content_arrangement(ContentArrangement::Dynamic);
table.add_row(vec![Cell::new("Hello"), Cell::new("How do you do")]);
```
And i would like to get the width of the second column of this table.

**Comment by Nukesor** [comment]
Nope, that's not possible yet.

The width of a column is currently only known at the end of the formatting process.
The whole logic for calculating this is completely encapsulated.

I'm curious, why do you want to access this information?

**Comment by Mohammadreza99A** [comment]
So I have a table and sometimes in one of cells of my table I want to insert an inner table. In that case I need to know the width of the parent table column in order to set the width of my inner table. Is there any other way to do this? 
```
fn pretty_json_print(json_obj: Result<JsonValue, serde_json::Error>) {
  let mut table = Table::new();
  table
    .load_preset(UTF8_FULL)
    .apply_modifier(UTF8_ROUND_CORNERS)
    .set_content_arrangement(ContentArrangement::Dynamic);

  for (key, value) in json_obj.unwrap().as_object().unwrap() {
    if value.is_array() {
      let mut inner_table = Table::new();
      // TODO: change the width of the inner table to be the width of the parent table column width
      inner_table
        .load_preset(UTF8_FULL)
        .apply_modifier(UTF8_ROUND_CORNERS)
        .set_content_arrangement(ContentArrangement::Dynamic)
        .set_table_width(80);
      for elem in value.as_array() {
        for obj in elem {
          inner_table.add_row(vec![Cell::new(obj)]);
        }
      }
      table.add_row(vec![Cell::new(key), Cell::new(inner_table)]);
    } else {
      table.add_row(vec![Cell::new(key), Cell::new(value)]);
    }
  }
  println!("{:?}", table);
}
```

**Comment by Nukesor** [comment]
Nested Dynamic Tables are actually not in the scope of ComfyTable :)

It's a feature that significantly increases the complexity of the code and it's more of an edge-case.
If somebody comes up with a neat implementation, that doesn't bloat up the code-base too much, I'll happily review these changes!

Until then, this will be a missing feature.

**Comment by DianaNites** [comment]
I use comfy-table and nested tables in my Linux modules project, it's a bit of a hack but seems to work and may be of interest

https://github.com/DianaNites/linux_modules#cli

**Comment by Mohammadreza99A** [comment]
> I use comfy-table and nested tables in my Linux modules project, it's a bit of a hack but seems to work and may be of interest
> 
> https://github.com/DianaNites/linux_modules#cli

Thanks for your response. Could you please let me know exactly how (or where in your code) you do nested tables with comfy_table ?

**Comment by DianaNites** [comment]
https://github.com/DianaNites/linux_modules/blob/main/src/main.rs#L200-L225

**Comment by Nukesor** [comment]
@Mohammadreza99A  This solution only works, if you don't work with dynamic content arrangement.
As soon as you enable that, you won't know the width of a column before actually rendering the table.
