### ISSUE TITLE
Question: Live refresh

### ISSUE THREAD

**Issue by Corfucinas** [Nukesor/comfy-table#30]
Is it possible to update a table without having to print the entire table?

For example, let's suppose I have a table 10x10 table, I will only update some contents of a `Cell`....can I render the same table?
Otherwise every update I would have to print the entire table to the terminal and clutter it

**Comment by Nukesor** [comment]
Doing this is not possible.
You have to take complete control over the terminal. for instance, `tui-rs` is a library that allows you to do this.

However, this is nothing that should be handled by comfy-table.
