### ISSUE TITLE
Question: `set_delimiter` in `Cell`

### ISSUE THREAD

**Issue by tk-nguyen** [Nukesor/comfy-table#31]
Hello, I'm having trouble understanding the documentation of this project 😓. What does the method [`get_delimiter`](https://docs.rs/comfy-table/2.1.0/comfy_table/struct.Cell.html#method.get_content) do? I'm understanding it as `Cell` will split itself into smaller `Cells` when it contains the `String` with the delimiter you set, with each `Cell` containing the tokens, but it seems that's not correct.

**Comment by Nukesor** [comment]
This doesn't split the Cell into multiple cells, but rather decides where to split the text _inside_ a Cell for newlines.

Normal text uses spaces ` ` as a delimiter for words.
However, in case of Mac-Addresses `ff:ff:ff:ff:ff:ff`, the delimiter would have to be `:`.

**Comment by Nukesor** [comment]
Check the [tests](https://github.com/Nukesor/comfy-table/blob/master/tests/custom_delimiter_test.rs) for this feature :)
They explain the situation quite well.

**Comment by tk-nguyen** [comment]
Thank you 😄 !
