### ISSUE TITLE
Offset table left margin

### ISSUE THREAD

**Issue by dmaahs2017** [Nukesor/comfy-table#32]
I'd first like to say, I love this library :). Just started using it for a personal project, to display CLI calendar where each cell is a date.

What I'd like is to be able to offset the left margin of the table. By adding leading whitespace to each line of the table when it is displayed.

I would suggest a function `Table::fmt_with_margin(left_margin: usize)` which is similar to `Table::trim_fmt()`

see PR: #34 
I'd be interesting in implementing this, but I'd like your thoughts first @Nukesor and @spenserblack

**Comment by Nukesor** [comment]
Thanks for the praise :D You're very welcome.

I already wrote a comment over [here](https://github.com/Nukesor/comfy-table/issues/35#issuecomment-869139704) regarding this issue, as those two are kind of connected :)

**Comment by dmaahs2017** [comment]
Closing this because I agree with @Nukesor assessment that this is outside of scope. And it becomes possible for the client to trivially implement this functionality when the `lines()` method is introduced
