### ISSUE TITLE
Solid inner borders modifier

### ISSUE THREAD

**Issue by ModProg** [Nukesor/comfy-table#39]
I would propose the following modifier for the UTF-8 Table:
```rs
const UTF8_SOLID_INNER_BORDERS: &str = "        │─         ";
```
This results in the following table:
```text
┌───────┬───────┐
│ Hello │ there │
╞═══════╪═══════╡
│ a     │ b     │
├───────┼───────┤
│ c     │ d     │
└───────┴───────┘
```
In Terminal with the lines actually connecting:
![Screenshot from Terminal with solid lines](https://user-images.githubusercontent.com/11978847/126872407-e1a8c4ca-c17b-4845-88e8-e160cbf2ebde.png)

**Comment by Nukesor** [comment]
Nice, looks like a reasonable proposal :)
Feel free to create a PR.

Don't forget to add the change to the `CHANGELOG.md` and to reference your profile + this issue
