### ISSUE TITLE
Consider using `#![forbid(unsafe_code)]`

### ISSUE THREAD

**Issue by jorgecarleitao** [Nukesor/comfy-table#42]
Since this does not seem to use or require `unsafe`. Advertise it on the README; makes it easier to audit :)

**Comment by Nukesor** [comment]
Done :)
Do you need a patch version for this or is it ok that this stays on `master` for now?

**Comment by jorgecarleitao** [comment]
Wow, thanks a lot @Nukesor ! No rush in releasing. There [was a PR](https://github.com/jorgecarleitao/arrow2/pull/251) to replace pretty-print and wanted to get a sense of the crate, so just cloned it and did a quick search. Your explanation was amazing; glad that it ended up on the README 👍 .

Thanks for doing this library and for the support.
