### ISSUE TITLE
colspan and rowspan

### ISSUE THREAD

**Issue by D1mon** [Nukesor/comfy-table#6]
need add the ability to merge cells vertically(rowspan) and horizontally(colspan).
https://html.com/tables/rowspan-colspan/

**Comment by Nukesor** [comment]
Well, feel free to tinker around a little bit.
I'm not sure that this is a feature that can be easily implemented, since this adds a lot of complexity to the dynamic arrangement calculation logic.

If you come up with a solution, feel free to create a PR.
