### ISSUE TITLE
cursive compatibility

### ISSUE THREAD

**Issue by realtica** [Nukesor/comfy-table#62]
Why is printing this chars? Do you have any clue?

![2022-01-28_19-40](https://user-images.githubusercontent.com/852446/151639778-21673127-4141-4aef-990e-974268e3f9dc.png)

In terminal works fine, but in [cursive](https://github.com/gyscos/cursive) app do not.

**Comment by Nukesor** [comment]
comfy-table uses [ANSI Escape Codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to style content.
This is generally the only way to style things in a commandline.

I assume that `cursive` app doesn't respect this kind of styling and rather uses their own styling rules.

**Comment by Nukesor** [comment]
Feel free to re-open this issue, if you find out which kind of styling `cursive` uses.

I might be open to include that styling language, if it's a common specification that's well established and widely used.

**Comment by realtica** [comment]
The problem was the backend ncurses, with crossterm backend works fine.
