### ISSUE TITLE
Background colors

### ISSUE THREAD

**Issue by realtica** [Nukesor/comfy-table#65]
The attribute Attribute::Bold breaks the background color

![2022-02-09_12-24](https://user-images.githubusercontent.com/852446/153256324-3b8e1261-de3e-4814-b011-786a2eb1ae62.png)

**Comment by Nukesor** [comment]
To be honest, this bug report is a little sparse.

I'm not sure where the problem is supposed to be, I don't know what your code looks like.
I don't see any bold text.

Could you be more specific?

**Comment by realtica** [comment]
According to image the header table id, title, description are the bold text.
The correct color is the dark-gray, the green color is the terminal color. I am using the crossterm library.
https://github.com/crossterm-rs/crossterm

**Comment by Nukesor** [comment]
You cannot use crossterm styling and comfy-table styling at the same time.

Comfy-table already uses crossterm's styling, but doesn't have any knowledge about external styling rules!

Please use comfy-table's internal styling and inform yourself on how ANSI escape codes work
