### ISSUE TITLE
Feature request: Format indentation

### ISSUE THREAD

**Issue by mcastorina** [Nukesor/comfy-table#7]
As far as I can tell from the docs, there is no way to set the indentation of the table. By indentation, I mean leading spaces to offset the table from the start of the line.

Example:
```
+----------------------+----------------------+------------------------+
| Header1              | Header2              | Header3                |
+----------------------+----------------------+------------------------+
| Center aligned       | This is another text | This is the third text |
| This is another text | Now                  | This is awesome        |
|                      | add some             |                        |
|                      | multi line stuff     |                        |
+----------------------+----------------------+------------------------+

vs indent=4

    +----------------------+----------------------+------------------------+
    | Header1              | Header2              | Header3                |
    +----------------------+----------------------+------------------------+
    | Center aligned       | This is another text | This is the third text |
    | This is another text | Now                  | This is awesome        |
    |                      | add some             |                        |
    |                      | multi line stuff     |                        |
    +----------------------+----------------------+------------------------+

```

**Comment by mcastorina** [comment]
I would be happy to contribute once there is confirmation this isn't already a feature.

**Comment by Nukesor** [comment]
Hmm. I'm not sure if this is something `comfy-table` should handle.
It's for formatting tables, not for doing anything around it.

You could simply go ahead and take the output, iterate through all lines and append 4 spaces on front of it.

If you still want to use the full terminal width, simply set the max width to the terminal width minus 4 by hand.

It just somehow doesn't feel right to add this to the library, since it has nothing to do with the table itself.

**Comment by mcastorina** [comment]
Hmm.. I see your argument and agree that iterating through the lines would be simple enough.

I was previously using prettytable-rs which has [indent](https://docs.rs/prettytable-rs/0.8.0/prettytable/format/struct.TableFormat.html#method.indent). That is why I suggested it here.

For reference if anyone else is looking to do this:
```rust
for line in table.to_string().split('\n') {
    println!("  {}", line);
}
```
