### ISSUE TITLE
Comparison with other 'table' libraries

### ISSUE THREAD

**Issue by danieleades** [Nukesor/comfy-table#76]
There are now a few libraries for pretty-printing tables to the console. It would be really helpful to have a bit of a comparison to allow users (including myself!) to determine which one to go for.

- [tabled](https://github.com/zhiburt/tabled)
- [prettytable-rs](https://github.com/phsym/prettytable-rs) (possibly unmaintained)
- [cli-table](https://github.com/devashishdxt/cli-table)
- [term-table-rs](https://github.com/RyanBluth/term-table-rs)
- [comfy-table](https://github.com/nukesor/comfy-table)
- etc...

**Comment by Nukesor** [comment]
Feel free to create a MR for this :)

Especially `tabled` did quite a lot of fancy stuff recently!

**Comment by Nukesor** [comment]
I can already give you a short summary on what `comfy-table` is about:

@danieleades Maybe it would make sense to aks for something like this from each project maintainer?
I think each maintainer is best suited to give a fair assessment of their library :)

### Comfy-table

One of comfy-table's big foci is on providing a minimalistic, but rock-solid library for building text-based tables.
This means that the code is very well tested, no `unsafe` and `unwrap` is only used if we can be absolutely sure that it's safe.
There're only two occurrences of `unsafe` in all of comfy-table's dependencies, specifically the `tty` interaction, which can also be explicitly disabled.

The other focus is on dynamic-length content arrangement.
This means that a lot of work went into building an algorithm that finds an optimal table layout for any given text and terminal width.

Other mentionable features are: Custom constraints for layouts, coloring/styling and table design presets.

**Comment by Nukesor** [comment]
See sibling issues:
https://github.com/zhiburt/tabled/issues/139
https://github.com/devashishdxt/cli-table/issues/26
https://github.com/RyanBluth/term-table-rs/issues/9

**Comment by Nukesor** [comment]
@danieleades prettytables-rs is indeed unmaintained. I already tried to communicate with the author roughly ~3 years ago, which is why I built this library in the first place.

I already went ahead and created a PR and Issue for deprecation, \
https://github.com/phsym/prettytable-rs/issues/139
https://github.com/phsym/prettytable-rs/pull/138

as well as a PR for a rust-sec advisory-db entry:
https://github.com/rustsec/advisory-db/issues/1173

**Comment by Nukesor** [comment]
@zhiburt @devashishdxt @RyanBluth
I think it would be a good idea to mention in our comparisons that `prettytable-rs` is indeed unmaintained, so there won't be any future confusion.

I'm not sure why the advisory-db entry isn't being merged, though. This would be the best solution in the long run.

**Comment by RyanBluth** [comment]
@Nukesor I added a comment to the `term-table-rs` repo, but I'll also post it here.

term-table-rs is pretty basic in terms of features. My goal with the project is to provide a good set of tools for rendering CLI tables, while also allowing users to bring their own tools for things like colours. One thing that is unique to term-table-rs(as far as I'm aware) is the ability to have different number of columns in each row of the table.

**Comment by Nukesor** [comment]
This worked out quite well in the end. I'm closing this issue :)

**Comment by wookietreiber** [comment]
It would be really nice if this could be added to the CLI book, like the [useful crates chapter](https://rust-cli.github.io/book/crates/index.html).

**Comment by Nukesor** [comment]
@wookietreiber Feel free to do so :) I definitely wouldn't mind!
