### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by InCogNiTo124** [Nukesor/comfy-table#84]
Hello, great project :+1: 

In order to keep it up to date, I suggest switching from `actions-rs` to `dtolnay/rust-toolchain` because, unfortunately, the former does not seem to be maintained anymore

I could easily help with that

**Comment by Nukesor** [comment]
Sorry for the late response, I wanted to respond on the same day but completely forgot about it :sweat_smile: 

It's a shame that `actions-rs` is somewhat unmaintained. I agree that a switch to `dtolnay/rust-toolchain` might be the right move.
