### ISSUE TITLE
How to remove border line and use `column separator`?

### ISSUE THREAD

**Issue by devgony** [Nukesor/comfy-table#86]
Recently i needed to remove border line and use custom column separator but I couldn't find any similar one except `set_delimter` which fetches different result that looks like parsing a char and replacing with carriage return.

1. Is there a way to remove all borders to print plain text only?
2. Is there a way to set custom column separator like this?
```sql
header1,header2
cell1,cell1
```
3. If 1 or 2 is not supported yet, can i contribute?

**Comment by Nukesor** [comment]
Check out [set_style](https://docs.rs/comfy-table/latest/comfy_table/struct.Table.html#method.set_style), the accompanying [TableComponent](https://docs.rs/comfy-table/latest/comfy_table/enum.TableComponent.html) and the convenience functions [load_preset](https://docs.rs/comfy-table/latest/comfy_table/struct.Table.html#method.load_preset) and [current_style_as_preset](https://docs.rs/comfy-table/latest/comfy_table/struct.Table.html#method.current_style_as_preset).

To be honest, looking at your example, you're not looking for a terminal table library, but rather a CSV library.
What you're trying to do breaks as soon as there're multiple lines of content.

**Comment by blueForestIcarus** [comment]
There is a reasonable use-case though: 
if someone wants to support printing both aligned and delimited output, and doesn't want to duplicate the table creation code.

**Comment by blueForestIcarus** [comment]
@devgony 
```
    let string = table
        .row_iter()
        .map(|row| {
            row.cell_iter()
                .map(Cell::content)
                .map(|cell| cell.escape_default().to_string())
                .collect::<Vec<_>>()
                .join(",")
        })
        .collect::<Vec<_>>()
        .join("\n");

    println!("{}", string);
```

**Comment by Nukesor** [comment]
This is easily achievable by either doing the formatting yourself in a few lines of code or by using other libraries on that support stuff like this.

Comfy-table's design goal is to be minimalistic and this request is the type of feature that's definitely feature-creep.
It doesn't have anything to do with a pretty-printed table, it's a CSV representation of your data, which comes with a lot of other caveats (e.g. how do you represent the characters in your content that you're using as a delimiter? Do we now have to do escaping? What should be the escape style? How do we represent newlines?)

Closing as won't do
