### ISSUE TITLE
Remove row dividers

### ISSUE THREAD

**Issue by affanshahid** [Nukesor/comfy-table#89]
Is it possible to remove row dividers completely? (not just have them as whitespace)

**Comment by Nukesor** [comment]
Take a look at the presets of the library. You can do this for all deviders.

Just set the style of all devider components to None and you should be good to go :)

**Comment by Nukesor** [comment]
See: https://docs.rs/comfy-table/latest/comfy_table/presets/constant.ASCII_BORDERS_ONLY_CONDENSED.html
