### ISSUE TITLE
[Feature] Handle ANSI escape codes from external libraries

### ISSUE THREAD

**Issue by blueforesticarus** [Nukesor/comfy-table#91]
#### Describe the bug

Column alignment breaks if printed text has formatting control codes.

#### Expected behavior

Text in a column contains parts formated with color/style using `console` crate. Alignment of later columns should be correct.

#### Code
```
use comfy_table::{Table, Row, Cell};
use console::Style;

fn main() {
    let mut table = Table::new();
    table.load_preset(comfy_table::presets::NOTHING);
    
    let mut row = Row::new();
    row.add_cell(Cell::new(
        "cell1"
    ));
    row.add_cell(Cell::new(
        "cell2"
    ));

    table.add_row(row);

    let mut row = Row::new();
    row.add_cell(Cell::new(
        format!("cell{}", console::style("3").bold().red())
    ));
    row.add_cell(Cell::new(
        "cell4"
    ));
    table.add_row(row);

    println!("{}", table);   
}
```
![image](https://user-images.githubusercontent.com/6549542/192279740-abdd47fd-72a4-4346-8a5b-2c17669a1855.png)

#### Additional context

- Operating System: nixos linux
- comfy-table version: 6.1.0

**Comment by blueForestIcarus** [comment]
I forked the repo and hacked together a fix for alignment using console::measure_text_width, though it likely still has a few issue.

Main problem I can find is with wrapping, 
![image](https://user-images.githubusercontent.com/6549542/192289585-98329eb2-adea-45aa-b220-43be340168bb.png)

**Comment by blueForestIcarus** [comment]
Trying the fix on my project, I see alignment issues as well, but I can't replicate them in an example.

**Comment by blueForestIcarus** [comment]
https://github.com/blueForestIcarus/comfy-table/blob/c62aed251e7e4ed7904d4bea31c3889181aed455/src/utils/formatting/content_split.rs#L159-L192 is the main problem.

**Comment by blueForestIcarus** [comment]
I wrote a version of split_long_word that respects ansi escape sequences, but it probably breaks other behavior somewhere

https://github.com/Nukesor/comfy-table/commit/9c01db6c0b318b6e1d8619fdb8022688ea4fca65

![image](https://user-images.githubusercontent.com/6549542/192316097-973c6fa7-dc33-4148-8c81-650e88b3e83e.png)

**Comment by Nukesor** [comment]
See https://github.com/Nukesor/comfy-table/pull/77
